# Generated by Django 3.2.16 on 2023-06-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_report', models.CharField(max_length=40, verbose_name='Номер запроса')),
                ('date_add_report', models.DateField(max_length=40, verbose_name='Дата поступления запроса')),
                ('about_report', models.CharField(blank=True, help_text='Необязательное поле', max_length=40, verbose_name='Краткое описание запроса или задачи')),
                ('type', models.CharField(max_length=40, verbose_name='Тип работы')),
                ('MD', models.CharField(blank=True, help_text='Номер редактируемой или новой ДЕ/ Результат работы', max_length=40, verbose_name='Результат работы')),
                ('author', models.CharField(max_length=40, verbose_name='Исполнитель')),
                ('report', models.CharField(blank=True, help_text='часы', max_length=40, verbose_name='Трудозатраты')),
                ('no_field', models.CharField(blank=True, max_length=40, verbose_name='не заполняется')),
                ('date_end_report', models.DateField(max_length=40, verbose_name='Дата закрытия запроса')),
            ],
        ),
    ]
