# Generated by Django 3.2.16 on 2023-06-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_add_report',
            field=models.DateField(verbose_name='Дата поступления запроса'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_end_report',
            field=models.DateField(verbose_name='Дата закрытия запроса'),
        ),
    ]
