# Generated by Django 3.2.16 on 2023-06-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20230617_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Тех.писатель2')),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='about_report',
            field=models.CharField(blank=True, help_text='Необязательное поле', max_length=256, verbose_name='Краткое описание запроса или задачи'),
        ),
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.author', verbose_name='Тех.писатель'),
        ),
    ]
