# Generated by Django 3.2.16 on 2023-06-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='AuthorRep',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='author',
            new_name='author_report',
        ),
    ]
