# Generated by Django 3.2.16 on 2023-06-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20230618_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorrep',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
