# Generated by Django 3.2.16 on 2023-06-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_authorrep_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorrep',
            options={'verbose_name': 'автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'тип работы', 'verbose_name_plural': 'Тип работ'},
        ),
    ]
